### ISSUE TITLE
Impl std::fmt::Display

### ISSUE THREAD

**Issue by xsbee** [poly000/lolicon_api#1]
https://github.com/poly000/lolicon_api/blob/5fe6dd9e39c079628daf17aed164e1f47778794a/src/datatype.rs#L212-L216

It would be witty to implement [`std::fmt::Display`](https://doc.rust-lang.org/std/fmt/trait.Display.html) thenceforth shall users be able to invoke `format!`.

**Comment by poly000** [comment]
> https://github.com/poly000/lolicon_api/blob/5fe6dd9e39c079628daf17aed164e1f47778794a/src/datatype.rs#L212-L216
> 
> It would be witty to implement [`std::fmt::Display`](https://doc.rust-lang.org/std/fmt/trait.Display.html) thenceforth shall users be able to invoke `format!`.

hi! thanks for your advice
I will implement this soon

**Comment by poly000** [comment]
hi! to_string is [automatically implemented for types: Display](https://doc.rust-lang.org/std/string/trait.ToString.html),
and at [#L193-#L210](https://github.com/poly000/lolicon_api/blob/5fe6dd9e39c079628daf17aed164e1f47778794a/src/datatype.rs#L193-L210) I have implemented Display...

so please allow me to close this as completed
